name: AgentKit CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          cd backend/app
          poetry config virtualenvs.create false
          poetry install
          pip install pytest pytest-asyncio pytest-cov

      - name: Run unit tests
        run: |
          cd backend/app
          # Créer un fichier .env.test avec des valeurs factices pour les tests
          cat > .env.test << EOF
          PROJECT_NAME=agentkit-test
          OPENAI_API_KEY=sk-test
          DATABASE_USER=postgres
          DATABASE_PASSWORD=postgres
          DATABASE_HOST=localhost
          DATABASE_PORT=5432
          DATABASE_NAME=test_db
          REDIS_HOST=localhost
          REDIS_PORT=6379
          MINIO_ROOT_USER=minioadmin
          MINIO_ROOT_PASSWORD=minioadmin
          MINIO_URL=localhost:9000
          MINIO_BUCKET=test-bucket
          BACKEND_CORS_ORIGINS=http://localhost:3000
          PDF_TOOL_EXTRACTION_CONFIG_PATH=./config/pdf_extraction_config.json
          AGENT_CONFIG_PATH=./config/agent_config.json
          SQL_TOOL_DB_ENABLED=false
          SQL_TOOL_DB_INFO_PATH=./config/sql_db_info.json
          SQL_TOOL_DB_URI=postgresql://postgres:postgres@localhost:5432/test_db
          PDF_TOOL_ENABLED=false
          PDF_TOOL_DATA_PATH=./data/pdf
          PDF_TOOL_DATABASE=./data/pdf_db
          EOF
          
          # Créer le répertoire config s'il n'existe pas
          mkdir -p config
          
          # Créer un fichier agent_config.json factice pour les tests
          cat > config/agent_config.json << EOF
          {
            "llm": {
              "model": "gpt-3.5-turbo",
              "temperature": 0.0,
              "streaming": true
            },
            "tools": {
              "sql_tool": {
                "enabled": false,
                "db_info_path": "./config/sql_db_info.json",
                "db_uri": "postgresql://postgres:postgres@localhost:5432/test_db"
              },
              "pdf_tool": {
                "enabled": false,
                "data_path": "./data/pdf",
                "database": "./data/pdf_db"
              }
            }
          }
          EOF
          
          # Créer un fichier pdf_extraction_config.json factice
          cat > config/pdf_extraction_config.json << EOF
          {
            "extraction_method": "simple"
          }
          EOF
          
          # Créer un fichier sql_db_info.json factice
          cat > config/sql_db_info.json << EOF
          {
            "tables": []
          }
          EOF
          
          # Exporter les variables d'environnement pour les tests
          export $(grep -v '^#' .env.test | xargs)
          
          # Afficher la structure des répertoires pour le débogage
          echo "Structure des répertoires:"
          find . -name "test*" -type d
          
          # Ignorer les avertissements de dépréciation pour les tests
          export PYTHONWARNINGS="ignore::DeprecationWarning,ignore::PendingDeprecationWarning"
          
          # Exécuter les tests avec le chemin correct (ajuster selon la structure réelle)
          if [ -d "app/tests/unit" ]; then
            python -m pytest app/tests/unit --cov=app --cov-report=xml
          elif [ -d "tests/unit" ]; then
            python -m pytest tests/unit --cov=app --cov-report=xml
          else
            echo "Répertoire de tests unitaires introuvable"
            find . -name "*test*.py" -type f
            # Tenter d'exécuter tous les tests disponibles
            python -m pytest --cov=app --cov-report=xml
          fi

      - name: Run integration tests
        run: |
          cd backend/app
          # Utiliser le même fichier .env.test créé précédemment
          export $(grep -v '^#' .env.test | xargs)
          
          # Ignorer les avertissements de dépréciation pour les tests
          export PYTHONWARNINGS="ignore::DeprecationWarning,ignore::PendingDeprecationWarning"
          
          # Exécuter les tests avec le chemin correct (ajuster selon la structure réelle)
          if [ -d "app/tests/integration" ]; then
            python -m pytest app/tests/integration --cov=app --cov-report=xml --cov-append
          elif [ -d "tests/integration" ]; then
            python -m pytest tests/integration --cov=app --cov-report=xml --cov-append
          else
            echo "Répertoire de tests d'intégration introuvable"
            # Ne pas échouer si les tests d'intégration n'existent pas
            exit 0
          fi

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: backend/app/coverage.xml
          fail_ci_if_error: false

  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install flake8 black isort mypy
          cd backend/app
          poetry install

      - name: Run linters
        run: |
          cd backend/app
          flake8 app
          black --check app
          isort --check-only app
          mypy app

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/backend
          tags: |
            type=ref,event=branch
            type=sha,format=short
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build
    if: (github.ref == 'refs/heads/develop' && github.event_name == 'push') || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'staging')
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name agentkit-staging-cluster --region us-west-2

      - name: Deploy to staging
        run: |
          # Set the image tag to the latest build
          IMAGE_TAG=$(echo ${{ github.sha }} | cut -c1-7)

          # Update the deployment manifest with the new image tag
          sed -i "s|image: ghcr.io/.*/backend:.*|image: ghcr.io/${{ github.repository }}/backend:sha-$IMAGE_TAG|g" k8s/staging/deployment.yaml

          # Apply the updated manifest
          kubectl apply -f k8s/staging/

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production')
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name agentkit-production-cluster --region us-west-2

      - name: Deploy to production
        run: |
          # Set the image tag to the latest build
          IMAGE_TAG=$(echo ${{ github.sha }} | cut -c1-7)

          # Update the deployment manifest with the new image tag
          sed -i "s|image: ghcr.io/.*/backend:.*|image: ghcr.io/${{ github.repository }}/backend:sha-$IMAGE_TAG|g" k8s/production/deployment.yaml

          # Apply the updated manifest
          kubectl apply -f k8s/production/
